name: app
description: A sample application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.7.2 <4.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^5.1.1
