name: dartpad
description: DartPad with Monaco Editor.
version: 1.0.0-12.dev
publish_to: none

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  analyzer: ">=6.0.0 <6.1.0"
  archive: ^3.4.4
  collection: ^1.18.0
  meta: ^1.10.0
  path: ^1.8.3

dev_dependencies:
  build_runner: ^2.4.6
  build_web_compilers: ^4.0.4
  lints: ^2.1.0
