name: dartpad
description: DartPad with Monaco Editor.
version: 1.0.0-dev.4
publish_to: none

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  analyzer: ^6.0.0
  js: ^0.6.7
  meta: ^1.9.1

dev_dependencies:
  build_runner: ^2.4.6
  build_web_compilers: ^4.0.4
  lints: ^2.1.1
