name: dartpad
description: DartPad with Monaco Editor.
version: 1.0.0-dev.0
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  js: ^0.6.7

dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.0
  lints: ^2.0.0
