name: dartpad
description: DartPad with Monaco Editor.
version: 1.0.0-10.dev
publish_to: none

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  analyzer_js: ^6.0.0
  archive: ^3.3.7
  collection: ^1.18.0
  js: ^0.6.7
  meta: ^1.9.1
  path: ^1.8.3
  web: ^0.1.4-beta

dev_dependencies:
  build_runner: ^2.4.6
  build_web_compilers: ^4.0.5
  lints: ^2.1.1

dependency_overrides:
  analyzer_js:
    path: ../analyzer_js
