name: dartpad
description: DartPad with Monaco Editor.
version: 1.0.0-13.dev
publish_to: none

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  analyzer: ^7.3.0
  archive: ^4.0.5
  collection: ^1.19.1
  meta: ^1.16.0
  path: ^1.9.1

dev_dependencies:
  build_runner: ^2.4.15
  build_web_compilers: ^4.1.4
  lints: ^5.1.1
